### ISSUE TITLE
Instance segmentation not being included?

### ISSUE THREAD

**Issue by Zs01t** [karolyartur/blender_annotation_tool#10]
My problem is that when in the exr_reader I try to access the channel 'i' it say the following: "TypeError: There is no channel 'BAT_ViewLayer.IndexMA.x' in the image" even though I clearly ticked the Instance segmentation checkbox in BAT. Did I misunderstood something or it is not workin as intended?

**Comment by karolyartur** [comment]
The 'BAT_ViewLayer.IndexMA.x' is the old name for the channel. The newest version of the exr_reader uses `BAT_ViewLayer.InstanceID.V` instead. You can use the `dev` branch of BAT to generate EXRs with the new channel name, so it is compatible with the newest version of exr_reader.

Alternatively, you could use a version of BAT before 234d6a207d180dff522f62e59a92089a5670dca8 together with the older version of exr_reader, but this is more tedious, and you miss out on new features implemented in the `dev` branch.

**Comment by karolyartur** [comment]
Merged #5.
Now master is compatible with exr_reader.
