### ISSUE TITLE
ClassID problem with materials

### ISSUE THREAD

**Issue by Zs01t** [karolyartur/blender_annotation_tool#11]
When importing an object with texture information Blender correctly adds the necessary materials to it. However when rendering this annotation, the classID channel of the EXR file for some reason takes the material into account, but only the first one. Same problem if you put more than one type of material onto your object in Blender.

**Comment by karolyartur** [comment]
@Zs01t, could you confirm whether 4a77482090874f1f625c4e84271afad83fa38fbd fixed the issue?

**Comment by karolyartur** [comment]
Confirmed.
